version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URI=mongodb://mongo:27017
      - DB_NAME=mydb
  mongo:
    image: mongo
    ports:
      - "27017:27017"