version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URI=mongodb://root:example@hostname:27017
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=mydb
  mongo:
    image: mongo
    ports:
      - "27017:27017"